name: bookofnim-ci
on:
  push:
    branches: [develop, deploy]
  pull_request:
    branches: [develop, deploy]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI / ${{ matrix.os }} / Nim${{ matrix.nimv }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10 # extra 5 minutes for compiling the devel branch

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] # macos-12
        nimv: [1.6.12, "devel"] # 1.9.3 doesnt work with choosenim

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          clean: true

      - name: Cache Nimble
        id: cache-nimble
        uses: actions/cache@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-${{ matrix.nimv }}-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.nimv }}

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nimv }}
          # repo-token: ${{ secrets.GITHUB_TOKEN }} # only required if API rate limit is breached

      - name: compile
        run: nim c ${GITHUB_WORKSPACE}/src/bookofnim.nim

      - name: test
        run: nim e ${GITHUB_WORKSPACE}/.github/scripts/test.nims

  docs:
    name: DOCS
    needs: CI
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1

    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest"]
        nimv: ["devel"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false
          fetch-depth: 1

      - name: Restore Nim Devel
        uses: actions/cache/restore@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-${{ matrix.nimv }}-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.nimv }}

      - name: Setup nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nimv }}

      - name: Create Docs
        run: nim e ${GITHUB_WORKSPACE}/.github/scripts/docs.nims
