name: bookofnim-commit-docs

on:
  pull_request_target:
    types: [closed]

jobs:
  if_merged:
    name: Commit docs
    if: (github.event.pull_request.merged == true) && (github.base_ref == 'develop')
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10 # extra 5 minutes for compiling the devel branch

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] # macos-12
        nimv: ["devel"] # 1.9.3 doesnt work with choosenim

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # @see https://github.com/actions/cache/issues/1152
      - name: Restore Docs
        id: restoredocs
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: false
          path: src/htmldocs
          key: ${{ github.head_ref }}

      # see above
      - name: Restore Nim Devel
        id: restorenim
        if: steps.restoredocs.outputs.cache-hit != 'true'
        uses: actions/cache/restore@v3
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-${{ matrix.nimv }}-${{ hashFiles('*.nimble') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.nimv }}

      # see above
      - name: Setup nim
        id: setupnim
        if: steps.restorenim.conclusion == 'success'
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nimv }}

      # see above
      - name: Create Docs
        id: createdocs
        if: steps.setupnim.conclusion == 'success'
        run: nim e ${GITHUB_WORKSPACE}/.github/scripts/docs.nims

      - name: Commit Docs and Push
        if: success() || steps.createdocs.conclusion == 'success' || steps.restoredocs.conclusion == 'success'
        shell: bash
        run: |
          # this required relaxing develop branch protection rules
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit --no-verify -m "Add(htmldocs): CI automation"
          git push -f
