name: bookofnim-commit-docs

on:
  pull_request_target:
    types: [closed]

jobs:
  if_merged:
    name: Commit docs
    if: (github.event.pull_request.merged == true) && (github.base_ref == 'develop')
    runs-on: ubuntu-latest
    steps:
      - name: Restore Docs
        uses: actions/cache/restore@v3
        with:
          fail-on-cache-miss: true
          path: src/htmldocs
          key: ${{ github.head_ref }}

      - name: Commit Docs and Push
        run: |
          git add -A
          git commit -a --no-verify -m "Add(htmldocs): use htmldocs from CI automation"
          git push -f
