name: bookofnim-commit-docs

on:
  pull_request_target:
    types: [closed]

jobs:
  if_merged:
    name: Commit docs
    if: (github.event.pull_request.merged == true) && (github.base_ref == 'develop')
    runs-on: ubuntu-latest
    steps:
      # @see https://github.com/actions/cache/issues/1152
      # - name: Restore Docs
      #   uses: actions/cache/restore@v3
      #   with:
      #     fail-on-cache-miss: true
      #     path: src/htmldocs
      #     key: ${{ github.head_ref }}

      # temporary: see above issue
      - name: Create Docs
        run: nim e ${GITHUB_WORKSPACE}/.github/scripts/docs.nims

      - name: Commit Docs and Push
        run: |
          git add -A
          git commit -a --no-verify -m "Add(htmldocs): use htmldocs from CI automation"
          git push -f
